### ISSUE TITLE
没有找到 keptab 的仓库，就在这里报告一个 keptab 小小的问题吧

### ISSUE THREAD

**Issue by shukebeta** [keptab/keptab-blog#1]
![image](https://user-images.githubusercontent.com/1399987/118187984-d31cbc00-b493-11eb-838d-534c9bbbee46.png)

我同时装了 onetab  和 keptab  但最近一段时间都没有使用。今天打开 keptab 发现有一些 0 tabs 的 collection。也许可以改进一下，不生成这种 0tabs 的collection？

**Comment by mywaiting** [comment]
@shukebeta 出现这样的问题实在不好意思，我详细排查一下。如果有结果，我将更新回来这里。多谢反馈！

**Comment by shukebeta** [comment]
![image](https://user-images.githubusercontent.com/1399987/119433620-b2ddde80-bd6a-11eb-8289-adc295ae1776.png)
没事没事，keptab确实挺快，我现在已经只用 keptab 了。
不过我后来把空的全删掉了。刚刚看到你的回复，我就又打开看了一下，如图在一堆正常的当中又发现了一个空的。
我的操作系统是 Ubuntu 20.04 的一个变种 Pop!_OS 20.04 LTS, 浏览器是 Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)

这个不紧急也不影响使用，不忙的时候你就看看

**Comment by shukebeta** [comment]
哈！我找到了必现的方法。在 KepTab 页用 Alt+W 热键尝试关闭这个TAB，这个TAB不会被关闭，但是会增加一个 0 Tabs 的记录。

**Comment by mywaiting** [comment]
在 KepTab 页用 Alt+W 热键尝试关闭这个TAB，确实可以稳定复现。Alt+W 热键本来是设置为发送全部窗口全部标签页至 Keptab 的，在处理自己的页面关闭的时候，逻辑有点问题了，我迟点详细查查，下个版本详细修复~

多谢你的反馈！！！多谢！！！

**Comment by mywaiting** [comment]
@shukebeta 已经修复此问题，新版本将稍后更新到浏览器商店

受到你的标题 **没有找到 keptab 的仓库** 的启发，我增加了 https://github.com/keptab/keptab/issues 这里仓库，方便收集问题

再次多谢你的反馈！
